
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Liste des commandes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <meta name="theme-color" content="#712cf9">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

    .navbar{
      position: fixed;
      z-index: 900;
      width:100%;
    }
    #back {
      text-decoration : none ;
      color : black
    }
    button {
      margin-left : 3rem;
    }
    a
    {
      margin-left : 3rem; 
    }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">A propos</h4>
          <p class="text-muted">A PROPOS DE NOUS,NOTRE STORE EST UN PETIT SITE WEB DYNAMIQUE SPECIFIIE EN VENTE EN LIGNE DES PRODUITS INFORMATIQUE</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Administration</h4>
          <ul class="list-unstyled">
            <li><a href="MiseAjour.php" class="text-white">back</a></li>
            <li><a href="deconnexion.php" class="text-white"></i> Deconnexion</a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
      <i class="bi bi-shop-window"></i> <strong>LA SOURIENTE</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">ESPACE ADMIN</h1>
        <p class="lead text-muted">Bienvenue admin  ,  vous pouvez faire la manipulation de notre store , "AJOUT DES PRODUITS , LES SUPPRIMER ET LES METTRE A JOUR "</p>
      </div>
      <a href="ajoutProduit.php"><button type="button" class="btn btn-outline-dark"><i class="bi bi-file-earmark-plus"></i> Ajouter un Produit</button></a>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <?php foreach($commandes as $commande) :?>
        <div class="col">
          <div class="card shadow-sm">
              <img  src="<?=$commande['image']?>">
            <div class="card-body"> 
            <p class="card-text"><b>Nom Client :</b><?=$commande['nomClient']?></p>
            <p class="card-text"><b>Nom Produit :</b><?=$commande['nomProduit']?></p>
              <p class="card-text"><b>Numéro de carte de client :</b><?= $commande['numcarte']?></p>
              <p class="card-text"><b>Adresse client :</b><?= $commande['adresse']?></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
               <a class="btn btn-outline-danger" href="commande.php?id_delete=<?=$commande['idClient'] ?>"><i class="bi bi-trash3"></i> Supprimer Commande</button></a>
             <!-- <button type="button" class="btn btn-outline-danger"><i class="bi bi-trash3"></i> Supprimer</button></a> -->
 
                </div>
              </div>
            </div>
          </div>
        </div>
        <?php endforeach; ?>
      



      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#" id="back">Back to top</a>
    </p>
  </div>
</footer>


    <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

      
  </body>
</html>
